name: Throne & Liberty X Feed to Discord

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch:

jobs:
  post-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Python Script
        run: |
          pip install feedparser requests
          python rss_to_discord.py
